/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import RabinKarp.RabinKarp;
import javax.swing.JOptionPane;
import textList.TextList;
import textList.TextNode;
    
/**
 *
 * @author luism
 */
public class TextVerification extends javax.swing.JFrame {
    
    TextList textList;
    String text1;
    String text2;
    
    public TextVerification(TextList tl) {
        initComponents();
        setLocationRelativeTo(null);
        
        textList = tl;
        
        titleList.removeAll();
        titleList.setListData(textList.getTitles().split(","));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titleList = new javax.swing.JList<>();
        text1Selector = new javax.swing.JButton();
        text2Selector = new javax.swing.JButton();
        verificationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VERIFICADOR DE TEXTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel1)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        titleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(titleList);

        text1Selector.setBackground(new java.awt.Color(255, 255, 255));
        text1Selector.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        text1Selector.setText("Selecionar Texto");
        text1Selector.setBorderPainted(false);
        text1Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1SelectorActionPerformed(evt);
            }
        });

        text2Selector.setBackground(new java.awt.Color(255, 255, 255));
        text2Selector.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        text2Selector.setText("Seleccionar segmento");
        text2Selector.setBorderPainted(false);
        text2Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2SelectorActionPerformed(evt);
            }
        });

        verificationButton.setBackground(new java.awt.Color(255, 255, 255));
        verificationButton.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        verificationButton.setText("Verificar");
        verificationButton.setBorderPainted(false);
        verificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificationButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Lista de Textos");

        backButtom.setBackground(new java.awt.Color(255, 255, 255));
        backButtom.setText("←");
        backButtom.setToolTipText("");
        backButtom.setBorderPainted(false);
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text1Selector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text2Selector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verificationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButtom))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButtom)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text1Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text2Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text1SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1SelectorActionPerformed
        String title = titleList.getSelectedValue();
        TextNode textNode = textList.search(title);
        
        if (textNode != null){
            text1 = textNode.text;
        } else {
            JOptionPane.showMessageDialog( null, "El titulo no esta relacionado con nigun texto.", "Error" ,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_text1SelectorActionPerformed

    private void text2SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2SelectorActionPerformed
        String title = titleList.getSelectedValue();
        TextNode textNode = textList.search(title);
        
        
        if (textNode != null){
            text2 = textNode.text;
        } else {
            JOptionPane.showMessageDialog( null, "El titulo no esta relacionado con nigun texto.", "Error" ,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_text2SelectorActionPerformed

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButtomActionPerformed

    private void verificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificationButtonActionPerformed
        RabinKarp rabinKarp = new RabinKarp();
        
        new RabinKarpResult(text2, rabinKarp.rabinKarp(text1, text2)).setVisible(true);
    }//GEN-LAST:event_verificationButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton text1Selector;
    private javax.swing.JButton text2Selector;
    private javax.swing.JList<String> titleList;
    private javax.swing.JButton verificationButton;
    // End of variables declaration//GEN-END:variables
}
